name: test

on:
  push:
    branches:
      - master
    paths:
      - '**.go'
      - '.github/**'
  pull_request:
    paths:
      - '**.go'
      - '.github/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.20', '1.21', '1.x']
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
      - run: go build
      - run: go test -cover ./...
